title: Lemming Labs
description: A pack of lemmings
theme: just-the-docs

url: https://lemming-labs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
